spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/polling_system"
    username: admin
    password: admin_password
  flyway:
    baseline-on-migrate: true
    baseline-description: Initial_Table_Creation